group=net.kyori
version=6.9.0-SNAPSHOT
description=Integration between the adventure library and Minecraft: Java Edition, using the Fabric and NeoForge modding systems

javadocPublishRoot=https://jd.advntr.dev/platform/

# supported versions for Modrinth publishing (comma separated)
modrinthMinecraftVersions=26.1-snapshot-4

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
