group=net.kyori
version=6.8.0
description=Integration between the adventure library and Minecraft: Java Edition, using the Fabric and NeoForge modding systems

javadocPublishRoot=https://jd.advntr.dev/platform/

# supported versions for Modrinth publishing (comma separated)
modrinthMinecraftVersions=1.21.11

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
